### PR TITLE
Add workers lifetime option

### PR DESCRIPTION
**Pull request by gi0baro**

### CODE REVIEW

**Comment by Zerotask** [comment]
That's a really nice addition. If I may suggest, could you also add another option for `The maximum amount of requests a worker will be kept alive before respawn` (#34)

**Comment by mikeckennedy** [comment]
Hey @gi0baro this is great. I've been waiting for this feature. 

One enhancement that I think would be really good, would be to add a jitter across workers.

Suppose you have 8 workers and set the restart time to 86,400 (1 day). After one day, as far as I can see, it will stop and restart all 8 workers at roughly the same time. I would much rather have a little bit of time between them to keep the jarring effect of a complete restart happening all at once. 

Could we get something like a `--workers-lifetime-jitter` which would allow us to specify an interval to vary the restart across.

For example: `--workers-lifetime-jitter 60` would have the workers restart across 60 seconds rather than all at once or just each one restart based on random(0, 60) seconds from when it started. 

Anything like this would be good I think (unless there is a default I didn't see in there somewhere).

**Comment by gi0baro** [comment]
Hey @mikeckennedy 👋 

The `--workers-lifetime` uses the *respawn strategy*, so it will respawn all the expired workers sequentially (starting the new one) respecting the `--respawn-interval` option (then shutting down the old one).
So if you just want to wait for a certain amount of time between the workers respawn, you can tune the `--respawn-interval` option. Eg: setting `--workers-lifetime 86400 --respawn-interval 30` will effectively make Granian wait 30 seconds before shutting down the old worker and thus proceed with the respawn of the next one.

Does this work for your use-case?

**Comment by mikeckennedy** [comment]
@gi0baro Perfect, that's more than enough for me. Thanks!

**Pull request merged**
