### PR TITLE
Add watchfile reload options

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
* Includes reload path option and filter options

### CODE REVIEW

**Review by gi0baro — COMMENTED** [review]
@Andrew-Chen-Wang thank you for your contribution. I have a couple of comments on this:
- I would rather use `Path` options in CLI instead of plain strings, given that both `click` and `typer` supports them and also allow additional validation on those (https://typer.tiangolo.com/tutorial/parameter-types/path/#path-validations)
- I'd like to see better descriptions for the new parameters, as IMHO it might be hard for users to understand the difference between `ignore-paths`, `ignore-dirs` and `ignore-entity-patterns`

**Comment by gi0baro** [comment]
> Hi thanks for the response. Will update the help text. In regards to the Path type, because watch file excepts globs, I didn't think Path would work.

From what I can see in `watchfiles` code, the only argument that might not be a path is the entity-patterns one.
Also, I just realised that the CLI parameters for the `ignore-*` should be optional with `None` as defaults, otherwise the check in here https://github.com/samuelcolvin/watchfiles/blob/main/watchfiles/filters.py#L115-L120 will remove defaults having those parameters as empty lists.

**Comment by Lendemor** [comment]
Hello, any update on this PR ? 

I've been testing to replace uvicorn with granian but this options would be needed :)

**Comment by gi0baro** [comment]
@Lendemor I was waiting for @Andrew-Chen-Wang to make the changes we discussed; I don't know if there are any updates from his side.

Given the amount of time this is opened, for sure it would need a rebase from the current master.

**Comment by Andrew-Chen-Wang** [comment]
would rec u just take my changes and make a PR :P not sure when i'll come back

**Comment by gi0baro** [comment]
Closing as superseded by #362

**Pull request closed without merging**
